codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        if_ci_failed: error
    
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "MyAdventures/mcpi/**/*"
  - "Server/**/*"
  - "**/__pycache__/**/*"
  - "**/*.pyc"
